### ISSUE TITLE
Unable to create a block

### ISSUE THREAD

**Issue by crysthala** [Frontrider/block-factory#1]
I'm super interested in trying out the "random ticking" feature for various nefarious purposes. Unfortunately, I'm either misunderstanding the documentation, or something isn't working.

My test file is at `block-factory\blocks\metallurgy\test.json`. Its contents are `{}`. I don't see any errors in the log, but the test block isn't appearing in the creative menu, and I tried `/give` to no avail. It's dangerous to go alone! Take [this](https://github.com/Frontrider/block-factory/files/3724709/latest.log)

Minecraft 1.14.4
Fabric Loader 0.6.3 build 167
Fabric API 0.4.0 build 240 (not listed in BF's dependencies on Curse, but the game crashes without it)
Block Factory 0.2.0

Many thanks! :)

**Comment by Frontrider** [comment]
Oh, Yeah. It got swapped to proper mc formatting in the meantime. It's `block-factory/<namespace>/blocks/<name>.json`.

The docs are not quite up to date on this one, as I'm still figuring things out (expect it until I give it a 1.0 release). The random ticking is included specifically, for the function api ;).

**Comment by crysthala** [comment]
Okay, I moved the file to `block-factory\metallurgy\blocks\test.json`. Still not working. Does it require assets (model/texture/localization) to work? I've been assuming it would just create an unlocalized/untextured block.

**Comment by crysthala** [comment]
Just tried it. Nope, that's not it, either. :thinking:

**Comment by crysthala** [comment]
Okay, so, I'm an idiot who forgot she moved the .jar to a different profile for testing issues. I just put it back, and now I'm getting a [crash](https://github.com/Frontrider/block-factory/files/3726790/crash-2019-10-14_18.50.49-client.txt).

**Comment by Frontrider** [comment]
That is an interesting crash. Maybe a mapping issue? I will check as soon as I can.

**Comment by Frontrider** [comment]
I know it now, gonna be an easy fix.

**Comment by Frontrider** [comment]
Should be fixed in the next version.

**Comment by crysthala** [comment]
The good news: no more crash. The bad news: still no test block, and Block Factory is not appearing in the list of loaded mods. I definitely have the .jar in the folder this time, but the only thing in the .jar is `META-INF\MANIFEST.MF`. Should I copy that file into the 0.2.0 .jar?

**Comment by Frontrider** [comment]
Something might be corrupted... I'll look into it.

**Comment by Frontrider** [comment]
It was, uploaded it again, and the size seems to be fine now. Try it when it's approved gain.

**Comment by crysthala** [comment]
Tried the new jar, and the crash is different now. Not sure why it's saying there's a `:` in the path, because the file is still at `block-factory\metallurgy\blocks\test.json`.

[crash-2019-10-16_22.25.47-client.txt](https://github.com/Frontrider/block-factory/files/3737291/crash-2019-10-16_22.25.47-client.txt)

**Comment by Frontrider** [comment]
I'm not exactly sure why that is happening We'll see. I only have like 1-1.5 hours/day to work on it now at most. So, sorry for this inconvenience.

**Comment by crysthala** [comment]
No worries! Cool stuff often takes time.

**Comment by Frontrider** [comment]
Should be fixed.

**Comment by crysthala** [comment]
Tried 0.3.0. [Crash report](https://github.com/Frontrider/block-factory/files/3742213/crash-2019-10-17_22.41.32-client.txt) and [log](https://github.com/Frontrider/block-factory/files/3742214/latest.log).
I can also reveal that it crashes when creating an item. 
[Report](https://github.com/Frontrider/block-factory/files/3742219/crash-2019-10-17_22.44.42-client.txt) and [log](https://github.com/Frontrider/block-factory/files/3742220/latest.log).

I looked up the line of code referenced in the crash reports. `:` is a special character thingy in Java, so does it need to be escaped `\:` to be recognized as part of a string?

**Comment by Frontrider** [comment]
It's something else.

**Comment by Nathan22211** [comment]
well this is probably why I'm having issues trying to create items with block factory

**Comment by Frontrider** [comment]
I see exactly where it happens, but I have no idea why at the moment. I'm using file templates to test it.

https://github.com/Frontrider/block-factory/blob/master/src/main/java/hu/frontrider/blockfactory/core/util/FileTemplateHelper.java#L22-L43

And yes, file templates are loaded through this as well.

**Comment by crysthala** [comment]
Probably another dumb n00b question, but... How come `replaceAll(":","")` is running on `namespace` and not `path`? I thought namespaces were supposed to have the `:` in them as part of the ID. Or am I totally misunderstanding what the code does?

**Comment by Frontrider** [comment]
No, there is no ":" in neither the namespace, nor the path. It is used as a separator, that is why you can't use it.

And I might have misread the log. It's hard to test as I can't reproduce it.

**Comment by crysthala** [comment]
Huh. Wonder where the colon's even coming from, then.

Weird that it's not reproducible. I use a number of different profiles in separate folders. The absolute path of the test file on my machine would be `A:\Users\Michelle\AppData\Roaming\.minecraft\Logical Issues\block-factory\test\blocks.json`. Could that affect it? What other factors might there be?

**Comment by crysthala** [comment]
Tested the profile directory thing, that's not it.

**Comment by crysthala** [comment]
Fixed in 0.4.1
